### ISSUE TITLE
Pangenome construction with no new insertions

### ISSUE THREAD

**Issue by SchreiberM** [wjian8/psvcp_v1.01#6]
Hi,
Thanks for making your scripts to generating a linear pangenome sequence available. 
It's working fine for me so far except I came across an issue today which I think is worth looking into.

I'm adding over 70 genomes together and at one stage reached a point where no new insertions were identified in comparison to the reference file. This meant the .bed file was empty and the "6update_ref_by_nucmer.py” part caused an error (EmptyDataError: No columns to parse from file).
It would be great if you could add a checkpoint in the script to skip those steps and generate the new reference from the previous reference without adding insertions.
 
Thanks,
Miriam

**Comment by wjian8** [comment]
Thank you for your advice.
I have add the checkpoint in the script "Refgenome_update_by_quest.sh"
You can re-download "Refgenome_update_by_quest.sh".

**Comment by SchreiberM** [comment]
Thank you. I've not tried it, but it looks similar to my improvised solution :).
